name: 'Deploy React + Node App to Azure'

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 20.x

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Frontend to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'frontendapp-100'
        slot-name: 'production'
        package: './react-todo-app/client/build'

    - name: Deploy Backend to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'backendapp-100'
        slot-name: 'production'
        package: './react-todo-app/backend.zip'
